# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'


target 'SwiftUITutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'
  pod 'Moya'
  pod 'Kingfisher'
  # pod 'YYKit'

  pod 'CombineCocoa'
  pod 'CombineExt'
  

  target 'SwiftUITutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUITutorialUITests' do
    # Pods for testing
  end

end
